window.MICRO_SLOWS = [
  {
    id: "listen-around",
    title: "周囲の音を聞く",
    instruction: "画面から目を離し、近くの音と遠くの音をひとつずつ聞く。",
    seconds: 60,
    senses: ["音"],
    intent: "通知や画面から注意を離し、周囲の環境に戻る。",
  },
  {
    id: "feel-hand-temperature",
    title: "手の温度を感じる",
    instruction: "手のひらをどこかに置いたまま、温かいところと冷たいところを感じる。",
    seconds: 45,
    senses: ["温度"],
    intent: "思考から身体感覚へ注意を移す。",
  },
  {
    id: "three-breaths-smell",
    title: "香りを三呼吸分だけ見る",
    instruction: "空気の匂いや重さを、三回の呼吸のあいだ観察する。",
    seconds: 30,
    senses: ["香り", "呼吸"],
    intent: "短い呼吸の単位で現在に戻る。",
  },
  {
    id: "feel-sole-pressure",
    title: "足裏の圧を感じる",
    instruction: "床に触れている足裏の、重い場所と軽い場所を感じる。",
    seconds: 75,
    senses: ["圧", "重さ"],
    intent: "身体の接地感を通して、緊張を下げる。",
  },
  {
    id: "watch-light-move",
    title: "光の変化を見る",
    instruction: "机や床に落ちる光をひとつ選び、ゆっくり動く気配を見る。",
    seconds: 50,
    senses: ["光", "視覚"],
    intent: "速い視線移動を止め、ゆっくりした変化に注意を置く。",
  },
  {
    id: "rest-shoulders",
    title: "肩の重さを預ける",
    instruction: "肩の力を抜き、肩の重さが椅子や背中に移っていくのを感じる。",
    seconds: 45,
    senses: ["重さ", "姿勢"],
    intent: "予定前の構えをゆるめる。",
  },
  {
    id: "feel-mouth-humidity",
    title: "口の中の湿度を感じる",
    instruction: "口の中の湿度や舌の位置を感じる。",
    seconds: 30,
    senses: ["湿度", "口腔感覚"],
    intent: "目立たずにできる身体感覚への移行。",
  },
  {
    id: "find-clothing-touch",
    title: "服の触れている場所を探す",
    instruction: "服が肌に触れている場所を感じ、場所による触れ方の違いを探る。",
    seconds: 40,
    senses: ["触覚"],
    intent: "外部刺激ではなく、すでにある感覚へ注意を向ける。",
  },
  {
    id: "feel-air-flow",
    title: "空気の流れを感じる",
    instruction: "肌に触れる空気が、どこからどこへ動いているかを感じる。",
    seconds: 60,
    senses: ["空気", "触覚"],
    intent: "目に見えない空気の動きを身体で捉える。",
  },
  {
    id: "wait-sound-end",
    title: "音の終わりを待つ",
    instruction: "近くで聞こえた音が消えるところまで待つ。",
    seconds: 50,
    senses: ["音", "時間"],
    intent: "次へ急ぐ反応を弱める。",
  },
  {
    id: "hold-warm-object",
    title: "温かいものを持つ",
    instruction: "カップや手元の温かいものを持ち、温度の移り方を見る。",
    seconds: 90,
    senses: ["温度", "触覚"],
    intent: "手元の小さな変化に滞在する。",
  },
  {
    id: "watch-shadow-edge",
    title: "影の輪郭を見る",
    instruction: "近くの影をひとつ選び、輪郭のぼやけ方を見る。",
    seconds: 60,
    senses: ["視覚", "光"],
    intent: "明確な意味を持たないものを見る。",
  },
  {
    id: "wait-next-breath",
    title: "呼吸を数えずに待つ",
    instruction: "呼吸を数えず、次の息が自然に来るのを待つ。",
    seconds: 45,
    senses: ["呼吸"],
    intent: "コントロールせずに生じるリズムを感じる。",
  },
  {
    id: "open-hand",
    title: "指の間の空気を感じる",
    instruction: "握っていた力を抜き、指の間の空気を感じる。",
    seconds: 35,
    senses: ["手", "空気"],
    intent: "小さな緊張を手放す。",
  },
  {
    id: "look-far",
    title: "遠くを見る",
    instruction: "画面より遠いものをひとつ見つけ、焦点をそこに置く。",
    seconds: 40,
    senses: ["視覚", "距離"],
    intent: "画面距離から離れ、視野を戻す。",
  },
  {
    id: "find-farthest-sound",
    title: "一番遠い音を探す",
    instruction: "一番遠くで鳴っている音を探す。",
    seconds: 50,
    senses: ["音", "距離"],
    intent: "音の意味ではなく、距離や層に注意を置く。",
  },
  {
    id: "watch-near-light-shadow",
    title: "近くの光や影を見る",
    instruction: "近くの光や影を見る。変化がなくても、そのままでよい。",
    seconds: 45,
    senses: ["光", "影", "視覚"],
    intent: "変化や発見を求めず、目の前の状態に滞在する。",
  },
  {
    id: "find-palest-color",
    title: "一番薄い色を見つける",
    instruction: "部屋の中で一番薄い色をひとつ見つけ、10秒だけ見る。色の名前は考えなくてよい。",
    seconds: 30,
    senses: ["色", "視覚"],
    intent: "名付けや判断から離れ、色そのものに注意を置く。",
  },
  {
    id: "feel-sound-direction",
    title: "音の方向を感じる",
    instruction: "聞こえてくる音が、どの方向から来ているように感じるかを探る。",
    seconds: 60,
    senses: ["音", "方向"],
    intent: "音の意味から離れ、音が来る方向に注意を向ける。",
  },
  {
    id: "listen-sound-layers",
    title: "音の重なりを聞く",
    instruction: "同時に聞こえる複数の音を、それぞれの層に分けて聞く。",
    seconds: 60,
    senses: ["音", "聴覚"],
    intent: "重なった音を分離して聞き、聴覚を研ぎ澄ます。",
  },
  {
    id: "feel-closed-eye-brightness",
    title: "目を閉じたときの明るさを感じる",
    instruction: "目を閉じたまま、まぶたの向こうの明るさの違いを感じる。",
    seconds: 45,
    senses: ["光", "視覚"],
    intent: "見ることをやめた状態に残る視覚感覚へ注意を向ける。",
  },
  {
    id: "find-overlooked-thing",
    title: "見落としそうなものを探す",
    instruction: "見えているものの中から、いちばん見落としそうなものを探す。",
    seconds: 60,
    senses: ["視覚", "注意"],
    intent: "視野の周縁にあるものへ注意を向ける。",
  },
  {
    id: "find-fading-sound",
    title: "消えそうな音を探す",
    instruction: "聞こえている音の中から、いちばん消えそうな音を探す。",
    seconds: 60,
    senses: ["音", "聴覚"],
    intent: "音の存在の薄さに注意を向ける。",
  },
  {
    id: "find-lightest-touch",
    title: "触れていないように感じる場所を探す",
    instruction: "触れているものの中から、いちばん触れていないように感じる場所を探す。",
    seconds: 60,
    senses: ["触覚", "接触"],
    intent: "接触の強弱や境界を感じる。",
  },
];
